apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tsa.name" . }}
  labels:
    {{- include "tsa.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tsa.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        {{- include "tsa.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "tsa.name" . }}
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: tyk-sre-assignment
          image: {{ include "tsa.image" . | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "--address=:8080"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}