{{- if .Values.selfNetworkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "tsa.name" . }}
  labels:
    {{- include "tsa.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ include "tsa.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  policyTypes: ["Ingress"]
  ingress:
    - from:
        - podSelector: {}   # same namespace
        {{- range .Values.selfNetworkPolicy.allowFromNamespaces }}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ . }}
        {{- end }}
      ports:
        - port: 8080
          protocol: TCP
{{- end }}
