apiVersion: v1
kind: Service
metadata:
  name: {{ include "tsa.name" . }}
  labels:
    {{- include "tsa.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "tsa.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
